### ISSUE TITLE
Why only Linux or Mac OS?

### ISSUE THREAD

**Issue by munik** [graalvm/graal-js-jdk11-maven-demo#21]
The README.md file says under Pre-requirements that Linux or Mac OS is required.

I was able to run this demo just fine on my Windows machine with JDK 11.0.2. Does the README just need to be updated, or is there a reason Windows is not officially supported yet?

**Comment by wirthi** [comment]
Hi @munik 

we are working on full Windows support currently. In principle, Graal is working on Windows (but other parts are not yet, like `native-image`). It is less mature than Linux and macOS, thus not officially supported (yet). If you find any problems, or are totally happy, let us know, this will help us to improve it.

-- Christian
