### ISSUE TITLE
Project Fails when run on rc13

### ISSUE THREAD

**Issue by kscarr73** [graalvm/graal-js-jdk11-maven-demo#22]
I changed the graalvm.version from rc10 to rc11 and rc12 and it built successfully.  When I change to rc13 it fails with:

```
[ERROR] testGraalPolyglotSpeed(com.mycompany.app.AppTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.oracle.truffle.api.TruffleOptions
	at com.mycompany.app.AppTest.testGraalPolyglotSpeed(AppTest.java:59)
```

The Nashhorn test runs, then fails with the above error.  This only occurs with rc13.

**Comment by boris-spas** [comment]
Thanks for the report! 
We are aware of the issue and a fix should be in for rc14.
