### ISSUE TITLE
How to work with PolyglotMap

### ISSUE THREAD

**Issue by wlnirvana** [graalvm/graal-js-jdk11-maven-demo#25]
I have something similar to the following, where `invokeFunction` returns an object `myDataObject` here) internally of the type `PolyglotMap`, but can only be typed statically as `Object`. I'm wondering how the data can be extracted out.

```java
        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("graal.js");
        URL url = Foobar.class.getClassLoader().getResource("foobar.js");
        engine.eval(Files.newBufferedReader(Paths.get(url.toURI()), StandardCharsets.UTF_8));

        Invocable inv = (Invocable) engine;
        var myDataObject =  (inv.invokeFunction("main", "testing data"));
```

**Comment by wirthi** [comment]
Hi,

`PolyglotMap` implements `java.util.Map` so that's how you can access it.

Best,
Christian
